### ISSUE TITLE
The basics section. Text Overflow.

### ISSUE THREAD

**Issue by saru95** [angular/angularjs.org#130]
In 'The Basics' section of the website, the printed text exceeds the screen limit instead of going to next line . 
![screen shot 2014-10-01 at 10 11 47 pm](https://cloud.githubusercontent.com/assets/6523503/4478998/eb475a5a-4989-11e4-8d4c-0daa145f07c5.JPG)

**Comment by Narretz** [comment]
https://github.com/angular/angularjs.org/commit/e2d9f01b6c407f886ca66bb1b8c89888fb24b778
