### ISSUE TITLE
how to implement cors with angular js ?

### ISSUE THREAD

**Issue by xiaoliuliu2050** [angular/angularjs.org#155]
this is my  js  example  :
  
angular.module('starter', [])
 .config(function($httpProvider) {
        $httpProvider.defaults.useXDomain = true;
        delete $httpProvider.defaults.headers
            .common['X-Requested-With'];
    })
 .controller('registerController',function($scope,$window,$location,$http)  {
        $scope.register=function (){
        $http({
                 method: 'GET',
                 url: 'http://ecs999.eicp.net:8000/hui2hui_register123',
                headers: {
                    withCredentials:true
                },
                 data: {
                     "userinfo":"xx"
                 } 
                 }).success(function(data) {
                        Window.alert(data);
                 }).error(function(data) {
                        Window.alert(data);
                 });

        };
})

when it executed ,
it  cannot visit the url adress  above ,whether the code above have something wrong or the the file on the server have something wrong ?

I want to make sure that the js file  is correct or not ?
if it is wrong ,how should I modify it?

**Comment by pkozlowski-opensource** [comment]
@xiaoliuliu2050 this is not the right place to ask those type of general support questions, see: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

For the CORS-related background info you might check http://www.html5rocks.com/en/tutorials/cors/
