### ISSUE TITLE
Docs are totally down

### ISSUE THREAD

**Issue by joshribakoff** [angular/angularjs.org#168]
I can't load the API docs at all. Also looks like the ability to view the cache from Google is disabled, so I currently don't even know of any mirrors I can use to view the docs.

![selection_492](https://cloud.githubusercontent.com/assets/4021306/7577893/98fd2dd8-f802-11e4-9f52-61ee83474a35.png)

**Comment by silverprize** [comment]
+1

**Comment by joshribakoff** [comment]
Here's a mirror http://devdocs.io/

**Comment by sinak** [comment]
+1

**Comment by lalithr95** [comment]
Docs are up! can any one close this issue ?
