### ISSUE TITLE
changing ng-controller "DocsVersionCtrl" changes maximum build version

### ISSUE THREAD

**Issue by abyss-outpost** [angular/angularjs.org#170]
After doing some exploring on the site it looks like the site links back to a previous version of the site every one goes backwards through versions, making the newer versions unreachable without hitting the back button.

**Comment by petebacondarwin** [comment]
This is true (for the docs website not this homepage site). Since each version of Angular docs is an independently hosted site and the versions are stored statically within the site, we do not currently have a way to get the most up to date list of versions.
