### ISSUE TITLE
Too Much Recursion on firefox

### ISSUE THREAD

**Issue by senateurritchie** [angular/angularjs.org#175]
Hi i build a big project with angularjs 1.2.28 
every thing i perfect on chrome and opera broswer but crash on firefox

"Error: too much recursion
s</ga.compile@http://yoobit.dev/src.php/v1-L6/jquery-1.11.3.min.js:2:21238
s</ga.select@http://yoobit.dev/src.php/v1-L6/jquery-1.11.3.min.js:2:21918
ga@http://yoobit.dev/src.php/v1-L6/jquery-1.11.3.min.js:2:7364
a.find@http://yoobit.dev/src.php/v1-L6.4/jquery.mobile-1.4.0.min.js:2:1957
.find@http://yoobit.dev/src.php/v1-L6/jquery-1.11.3.min.js:2:23658
t@http://yoobit.dev/src.php/v1-L5/jquery.tinymce.min.js:1:106
t/</e.fn[i]@http://yoobit.dev/src.php/v1-L5/jquery.tinymce.min.js:1:1393
t/</e.fn[i]@http://yoobit.dev/src.php/v1-L5/jquery.tinymce.min.js:1:1408
t/</e.fn[i]@http://yoobit.dev/src.php/v1-L5/jquery.tinymce.min.js:1:1408

what is the problem please.

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/angular.js/issues/12579#issuecomment-130631395
