### ISSUE TITLE
when I try to Access a page the page appears to be broken when i refresh it multiple times.

### ISSUE THREAD

**Issue by SibuStephen** [angular/angularjs.org#183]
Please see the screenshot below, I was able to reproduce this error , when i was accessing this page -> https://docs.angularjs.org/api/ng/directive/ngHref, when i refreshed it a couple of times, it appears to be broken somehow (with error - Uncaught Error: [$injector:modulerr]).(Found this issue on Ubuntu 14 on Chrome Version 44.0.2403.155 (64-bit)).
![screenshot from 2015-12-21 13 04 50](https://cloud.githubusercontent.com/assets/6688976/11926687/ca167006-a7ec-11e5-964b-cd6abccd71af.png)

**Comment by petebacondarwin** [comment]
Is this still happening for you?

**Comment by petebacondarwin** [comment]
It looks like some of the scripts (particularly the angular.js file) is not loading or executing properly.

**Comment by SibuStephen** [comment]
@petebacondarwin  it appears sometimes. when a page is continuously refreshed, and yes the changes is as mentioned by you because the file is not loading properly.

**Comment by petebacondarwin** [comment]
It sounds to me like it is a connection issue rather than a specific issue with this website.

**Comment by SibuStephen** [comment]
Yes if the error is not reproducible then i guess there is no issue.This can be closed.
