### ISSUE TITLE
add license note to all live examples

### ISSUE THREAD

**Issue by naomiblack** [angular/angularjs.org#184]
All of our live examples (codepen, plunkr) must include the following statement at the end of each file:

```
Copyright 2016 Google Inc. All Rights Reserved.
Use of this source code is governed by an MIT-style license that can be found in the LICENSE file at http://angular.io/license
```

I have the license hosted on angular.io, but you could point to a more angularjs-specific hosted copy if you prefer. It doesn't matter -- the text for all our licenses is the same.

**Comment by petebacondarwin** [comment]
Fixed in angularjs.org by https://github.com/angular/angularjs.org/commit/4473f530893cbb017178f1a8a3c690ac7c7cc0e7

**Comment by petebacondarwin** [comment]
I guess we still need to do it for all the Plunkers from the angular.js docs app too? Or did someone do that already?

**Comment by petebacondarwin** [comment]
Closing and opening a new issue for this in angular.js project.
