### ISSUE TITLE
UX issues with the dialog box appearing on the landing page

### ISSUE THREAD

**Issue by daminisatya** [angular/angularjs.org#195]
When clicked on "Download AngularJS1", a dialog box pops out. But there is no way of closing the dialog box. Would be better if a "X" button is placed at the edge of the dialog box header. 

![angular](https://cloud.githubusercontent.com/assets/6227784/14315243/a72a73f4-fc19-11e5-9fc1-e443236c0ab6.PNG)

**Comment by daminisatya** [comment]
Also there is no tooltip when i hover over the "?" icon

**Comment by Narretz** [comment]
Thanks, the popover / tooltip should be fixed and a close button added as soon as the build has completed
