### ISSUE TITLE
[typo?] hint spans show a title with 'hover'

### ISSUE THREAD

**Issue by Twiknight** [angular/angularjs.org#197]
When I click the highlighted 'me' in '_Hint_: click me' on the Homepage, it shows a popover titled with 'Hover'.

Is that by design or just a typo?

 I found the `popover-title` set to "Hover" in source, 
but err... it is a little confusing to see "Hover" while one should actually click.

```javascript
.directive('hint', function() {
    return {
      template: '<em>Hint:</em> Click ' +
          '<code class="nocode" popover-title="Hover" popover-trigger="outsideClick" popover-append-to-body="true"' +
          'uib-popover="Click highlighted areas in the code for explanations.">me</code>.'
    };
  })
```

https://github.com/angular/angularjs.org/blob/master/src/js/homepage.js#L373

**Comment by gkalpak** [comment]
It is indeed a left-over from 5c34bde. The hints used to display on `mouseenter`.
That said, I think it's amuch better user experience not having to click/unclick on the dozen of hints in the code, so we should limit the click-to-open behavior just to the download modal popovers (to fix #119).
