### ISSUE TITLE
Unable to access docs

### ISSUE THREAD

**Issue by dmlb** [angular/angularjs.org#202]
![screen shot 2016-06-13 at 1 14 20 pm](https://cloud.githubusercontent.com/assets/4835191/16016656/1b471000-316a-11e6-8f4a-c1f0338b1a48.png)
![screen shot 2016-06-13 at 1 14 42 pm](https://cloud.githubusercontent.com/assets/4835191/16016657/1b50aec6-316a-11e6-87d1-f8cb13f93b6d.png)

undefined in path causing 404

**Comment by rhencke** [comment]
Problem appears to be in https://docs.angularjs.org/api lines 36-42.

**Comment by andrew-luhring** [comment]
I tweeted to them. If you have slack, maybe hit the angular team up on there too?

**Comment by dmlb** [comment]
no slack here.
I also tweeted, and there have been various tweets from others furthest back I've noticed is an hour
https://twitter.com/search?f=tweets&vertical=default&q=angularjs%20docs&src=typd

**Comment by pkozlowski-opensource** [comment]
Just leaving a comment to let you know that the team is aware about the pb and working on resolving it. Stay tuned for updates.

**Comment by gkalpak** [comment]
The docs are back online. Thx for bringing this to our attention.
