### ISSUE TITLE
Add AngularJS in Action under Books?

### ISSUE THREAD

**Issue by amandeepmittal** [angular/angularjs.org#209]
Angularjs in Action by Lukas Ruebbelke is good resource and provides a hands-on-experience. It'll be a good fit under "General Learning Resources > Books".

**Comment by gkalpak** [comment]
This repo is about the home page. The content of the developer guide is maintained in https://github.com/angular/angular.js. Feel free to open a pull request there (you need to edit [this file][1]).

[1]: https://github.com/angular/angular.js/blob/master/docs/content/guide/external-resources.ngdoc#L117

**Comment by amandeepmittal** [comment]
Thanks for the link.
