### ISSUE TITLE
AngularJS vs Angular strip

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angularjs.org#212]
@alexwolfe I have landed #210 but we still have one outstanding task:

> We'd like a thin strip right under the header (menus) that will say something like "This site and all of its contents are referring to AngularJS (version 1.x), if you are looking for the latest Angular, please visit angular.io." We can tweak the text later, but let's start with this.

**Comment by alexwolfe** [comment]
Sounds good, will make this update today 👍🏻

**Comment by alexwolfe** [comment]
Ok, this branch is ready for review and also addresses some mobile issues
that I noticed:
https://github.com/angular/angularjs.org/pull/214

- Alex

**Comment by Narretz** [comment]
Fixed
