### ISSUE TITLE
CSS issues on the download button?

### ISSUE THREAD

**Issue by naomiblack** [angular/angularjs.org#213]
On my macbook air at standard width, the download button looks like this:
![image](https://cloud.githubusercontent.com/assets/2286589/22392437/05767318-e4ae-11e6-9fff-f38936df41c1.png)

Looks like a CSS issue?

@petebacondarwin @alexwolfe

**Comment by alexwolfe** [comment]
I'll take a look and address it with the other changes I'm making. Thanks.

- Alex

**Comment by petebacondarwin** [comment]
This was my fault when fixing up the e2e tests. It has now been resolved.

**Comment by alexwolfe** [comment]
Yup, found another bug that was introduced, a max width of 300px
(arbitrary) that was added to the search bar. I'm removing that as it not
only interferes with the design (making it look really bad on desktop) it
also breaks mobile.

On Sat, Jan 28, 2017 at 8:58 AM, Pete Bacon Darwin <notifications@github.com

**Comment by alexwolfe** [comment]
Ok, added the site notice and addressed a few mobile issues that popped up.
PR is here and ready for review. Thanks.

https://github.com/angular/angularjs.org/pull/214

- Alex

**Comment by petebacondarwin** [comment]
I added the 300px maxwidth because there were complaints it was too wide on desktop. Your fix will need to address that.

**Comment by alexwolfe** [comment]
Where were the complaints coming from? Was it a design complaint or
usability issue? I'll look into it but from a design standpoint it's more
balanced and inline with other material sites.

**Comment by alexwolfe** [comment]
Can you forward me the complaints or direct the person my way, should make
it easier to address this properly and give me the context for the problem.
Thanks.

Alex

**Comment by petebacondarwin** [comment]
Primarily @igorminar but I agree it looked very wide. It almost filled the
toolbar.

**Comment by alexwolfe** [comment]
Ok, thanks for the background. Lets try to address these in the original PR in the future, that will allow me to address issues related to my branch and reduce turnaround and reduce new bugs. My plan for this is: 

Move the search to the right side and reduce the width, this should accomplish two things: 
1. The navigation links will always be in view and the same location (flush left) regardless of screen width. 
2. This will be consistent with the other google dev sites. 

@IgorMinar let me know if that sounds right, if you need a design mock before implementation, let me know. Thanks.
