### ISSUE TITLE
Supported Status for Versions

### ISSUE THREAD

**Issue by cjsfj** [angular/angularjs.org#220]
Greetings -

It would be great if angularjs.org could maintain a simple page that indicates AngularJS versions and their EOL/Security Patch/LTS status.

For example, PHP has a similar page here: http://php.net/supported-versions.php

It clearly outlines the bug fix / security patch strategy for each supported version of PHP. 

For angular, there are blog entries that elude to support (security fixes for 1.2.x in the 1.6.0 announcement post, for example). But even if there was just a list, not necessarily with timelines, of the most recent version of each significant release of Angular, and the current status of support for that release, it would make it simple for a developer to choose a supported version... 

Or in our case, justify staying on a 1.2.x version because security patches are still maintained.

Thanks!

C

**Comment by Narretz** [comment]
I think this should be part of the angular/angular.js repo as it changes with the versions.

**Comment by cjsfj** [comment]
@Narretz No issue from me. One could make an argument to have it in either or both locations. However it's not published anywhere today in an overt/obvious location that I could find. I'm happy to cross-post this request if needed.

**Comment by Narretz** [comment]
Yes, please open in angular/angular.js instead

cjsfj <notifications@github.com> schrieb am Do., 15. Juni 2017 19:47:
