### ISSUE TITLE
https://www.angularjs.org/ is down URGENT!!!

### ISSUE THREAD

**Issue by Sumeetgrg** [angular/angularjs.org#221]
**Our production is halted!** URGENT!!

We are referring domain: https://code.angularjs.org/1.2.12.. 
https://angularjs.org/ is down too..

**Comment by gkalpak** [comment]
As mentioned on the site, you should not rely on `code.angularjs.org` for production. You should switch to using a CDN (or a locally hosted file).

We are investigating. It is probably related to infrastructure changes or config changes done in angular/angular.js, so let's track it [here][1] (until we know better :smiley:).

[1]: https://github.com/angular/angular.js/issues/16205
