### ISSUE TITLE
Inconsistent Navigation Menu Links

### ISSUE THREAD

**Issue by albertyw** [angular/angularjs.org#80]
The dropdown navigation menu links are pretty inconsistent going from page to page.  For example
On the home page, clicking Learn -> Home is the same as angularjs.org (not docs.angularjs.org)
Clicking Learn -> Tutorial is the same as Develop -> Tutorial - http://docs.angularjs.org/tutorial (or was that on purpose?)

This is a more generalized problem of issue #65

**Comment by Narretz** [comment]
Fixed on org, shorty fixed in the docs app, too
